fix: refactor org-chart function
felleslosninger/tlp-organisation-chart pull request #86
Opened 2024-04-03 12:25 UTC by jensmo98

2024-04-04 13:44 UTC, Barsnes requested changes
Reviewed a bit, let's do 30 minutes tomorrow 🐬

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +  prefix: string,
I think we should make all functions accept an object. That way we don't have to make sure the order is correct, and we don't need to send everything when we don't need to.
It will also make it so we can make some things optional, and typescript can better help us.
We can also then take better use of variables named the same as the key in the object.

This is for every function current in use with more then 3 parameters.

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +  isMobile && tocBox.classList.add(`${prefix}-toc-box-mobile`);
```suggestion
  tocBox.classList.add(`${prefix}-toc-box`, isMobile && `${prefix}-toc-box-mobile`);
```

`classList.add` takes a comma seperated list of strings, so we can add the `isMobile` check on the same line.

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +      return `${prefix}-row ${prefix}-row-last-${rowLength}${isLaptop ? '-laptop' : isTablet ? '-tablet' : ''}`;
`${isLaptop ? '-laptop' : isTablet ? '-tablet' : ''}` should be changed to a const higher up in this function - since we are doing this check in multiple places, we can create a variable for it.

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +}
Can this be a switch statement? Long terniaries are hard to read and understand

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +    return className;
I don't think we need the space before every variable here, since we can use `classList.add()`, which takes a comma seperated list of strings.
It currently gives us something we need to worry about, the leading space.

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +function getDevise(
Should be `getDevice`

2024-04-04 13:44 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +      const devise = getDevise(mainContainerWidth, allowedBreakpoints);
Should be `device`

2024-04-05 06:05 UTC, Barsnes commented on packages/org-chart/src/orgChart.ts
> +  isMobile && tocBox.classList.add(`${prefix}-toc-box-mobile`);
Found out this does not work, because it will "throwa a "SyntaxError" DOMException if one of the arguments is the empty string."

2024-04-05 06:43 UTC, jensmo98 commented on packages/org-chart/src/orgChart.ts
> +    return className;
i use className += createNodeLines(...), and not add when i call this function. This means that I cannot return an empty string etc.. Maby I should replease all occuransces of className += ... with classList.add() ?

2024-04-08 10:10 UTC, Barsnes approved these changes
Some more things that could be done here, but this PR is big enough for now. We can do more changes in a later PR

2024-04-09 09:13 UTC, merged