docs: update documentatation
felleslosninger/tlp-organisation-chart pull request #94
Opened 2024-04-15 11:21 UTC by jensmo98

Updated documentation in md file for storefront. Can and should be copied to README. 

1. Complimented with more documentation about how to construct the JSON for org chart.
2. Updated old documentation

2024-04-19 06:23 UTC, Barsnes requested changes
Overall good additions, left some suggestions, some for spellingmistakes, and a few questions about column counts.

2024-04-24 09:53 UTC, jensmo98 commented on apps/storefront/app/routes/dokumentasjon.mdx
> +- If not the column contains the root node, and is one of maximum two columns in the row, you have the ability to align it.
Better?

2024-04-25 06:51 UTC, Barsnes commented on apps/storefront/app/routes/dokumentasjon.mdx
> +- If not the column contains the root node, and is one of maximum two columns in the row, you have the ability to align it.
Yes, looks great!

2024-04-25 06:52 UTC, Barsnes approved these changes
Looks great, good work 🐑

2024-05-03 08:21 UTC, merged